package dev.nexflow.order;
import dev.nexflow.audit.AuditService; import dev.nexflow.common.ApiException; import dev.nexflow.inventory.InventoryService; import dev.nexflow.product.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.time.LocalDate; import java.util.*; import java.util.concurrent.ThreadLocalRandom;
@Service public class OrderService {
 private final OrderRepository orders; private final ProductRepository products; private final InventoryService inventory; private final AuditService audit;
 public OrderService(OrderRepository o,ProductRepository p,InventoryService i,AuditService a){orders=o;products=p;inventory=i;audit=a;}
 @Transactional(readOnly=true) public List<OrderDtos.View> list(){return orders.findAllByOrderByCreatedAtDesc().stream().map(this::view).toList();}
 @Transactional public OrderDtos.View create(OrderDtos.CreateRequest r,String user){OrderEntity order=new OrderEntity();order.setCode(code());order.setCustomerName(r.customerName());order.setCustomerEmail(r.customerEmail());order.setStatus(OrderStatus.CREATED);BigDecimal total=BigDecimal.ZERO;
  for(var requested:r.items()){Product p=products.findById(requested.productId()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Product not found"));if(!p.isActive())throw new ApiException(HttpStatus.BAD_REQUEST,"Inactive product: "+p.getName());inventory.reserve(p,requested.quantity(),order.getCode(),user);OrderItem item=new OrderItem();item.setProductId(p.getId());item.setProductName(p.getName());item.setQuantity(requested.quantity());item.setUnitPrice(p.getPrice());item.setTotal(p.getPrice().multiply(BigDecimal.valueOf(requested.quantity())));total=total.add(item.getTotal());order.addItem(item);}order.setTotal(total);order=orders.save(order);audit.log(user,"CREATE","ORDER",order.getId().toString(),"Created "+order.getCode()+" and reserved inventory");return view(order);}
 @Transactional public OrderDtos.View updateStatus(UUID id,OrderStatus next,String user){OrderEntity order=orders.findOneById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Order not found"));OrderStatus current=order.getStatus();if(!allowed(current,next))throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid transition: "+current+" -> "+next);
  if(next==OrderStatus.CANCELLED){for(OrderItem item:order.getItems())inventory.release(products.findById(item.getProductId()).orElseThrow(),item.getQuantity(),order.getCode(),user);}if(next==OrderStatus.SHIPPED){for(OrderItem item:order.getItems())inventory.ship(products.findById(item.getProductId()).orElseThrow(),item.getQuantity(),order.getCode(),user);}order.setStatus(next);audit.log(user,"STATUS_CHANGE","ORDER",order.getId().toString(),order.getCode()+": "+current+" -> "+next);return view(order);}
 private boolean allowed(OrderStatus current,OrderStatus next){if(current==next)return true;if(next==OrderStatus.CANCELLED)return EnumSet.of(OrderStatus.CREATED,OrderStatus.PAYMENT_APPROVED,OrderStatus.SEPARATING,OrderStatus.READY_TO_SHIP).contains(current);return switch(current){case CREATED->next==OrderStatus.PAYMENT_APPROVED;case PAYMENT_APPROVED->next==OrderStatus.SEPARATING;case SEPARATING->next==OrderStatus.READY_TO_SHIP;case READY_TO_SHIP->next==OrderStatus.SHIPPED;case SHIPPED->next==OrderStatus.DELIVERED;default->false;};}
 private String code(){return "NX-"+LocalDate.now().toString().replace("-","")+"-"+ThreadLocalRandom.current().nextInt(1000,9999);}
 public OrderDtos.View view(OrderEntity o){return new OrderDtos.View(o.getId(),o.getCode(),o.getCustomerName(),o.getCustomerEmail(),o.getTotal(),o.getStatus(),o.getItems().stream().map(i->new OrderDtos.ItemView(i.getProductId(),i.getProductName(),i.getQuantity(),i.getUnitPrice(),i.getTotal())).toList(),o.getCreatedAt(),o.getUpdatedAt());}
}
