package dev.nexflow.inventory;
import dev.nexflow.audit.AuditService; import dev.nexflow.common.ApiException; import dev.nexflow.product.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class InventoryService {
 private final ProductRepository products; private final InventoryMovementRepository movements; private final AuditService audit;
 public InventoryService(ProductRepository p,InventoryMovementRepository m,AuditService a){products=p;movements=m;audit=a;}
 @Transactional public void adjust(InventoryDtos.AdjustmentRequest r,String user){Product p=products.findById(r.productId()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Product not found"));int next=p.getStockQuantity()+r.quantity();if(next<p.getReservedQuantity()||next<0)throw new ApiException(HttpStatus.BAD_REQUEST,"Adjustment would make stock lower than reserved quantity");p.setStockQuantity(next);record(p,MovementType.ADJUSTMENT,r.quantity(),r.reason(),user);audit.log(user,"ADJUST","INVENTORY",p.getId().toString(),"Stock adjusted by "+r.quantity()+" for "+p.getSku());}
 @Transactional public void reserve(Product p,int qty,String ref,String user){if(p.availableQuantity()<qty)throw new ApiException(HttpStatus.CONFLICT,"Insufficient stock for "+p.getName());p.setReservedQuantity(p.getReservedQuantity()+qty);record(p,MovementType.RESERVATION,qty,ref,user);}
 @Transactional public void release(Product p,int qty,String ref,String user){p.setReservedQuantity(Math.max(0,p.getReservedQuantity()-qty));record(p,MovementType.RELEASE,qty,ref,user);}
 @Transactional public void ship(Product p,int qty,String ref,String user){if(p.getReservedQuantity()<qty||p.getStockQuantity()<qty)throw new ApiException(HttpStatus.CONFLICT,"Invalid stock reservation for "+p.getName());p.setReservedQuantity(p.getReservedQuantity()-qty);p.setStockQuantity(p.getStockQuantity()-qty);record(p,MovementType.OUT,-qty,ref,user);}
 public List<InventoryDtos.MovementView> recent(){return movements.findTop100ByOrderByCreatedAtDesc().stream().map(m->new InventoryDtos.MovementView(m.getId(),m.getProduct().getId(),m.getProduct().getName(),m.getProduct().getSku(),m.getType().name(),m.getQuantity(),m.getReference(),m.getCreatedBy(),m.getCreatedAt())).toList();}
 private void record(Product p,MovementType t,int q,String ref,String user){InventoryMovement m=new InventoryMovement();m.setProduct(p);m.setType(t);m.setQuantity(q);m.setReference(ref);m.setCreatedBy(user);movements.save(m);}
}
